// Comprehensive Fallback Mock Data for Big Market 👌 E-Commerce Platform

export const MOCK_CATEGORIES = [
  { _id: 'cat-1', name: 'Dairy & Breakfast', slug: 'dairy-breakfast', icon: '🥛', description: 'Fresh Milk, Curd, Butter, Cheese & Paneer' },
  { _id: 'cat-2', name: 'Oils & Spices', slug: 'oils-spices', icon: '🧂', description: 'Kachi Ghani Oils, Sunflower Oil, Pure Ghee & Spices' },
  { _id: 'cat-3', name: 'Snacks & Munchies', slug: 'snacks-munchies', icon: '🍿', description: 'Namkeen, Chips, Biscuits & Roasted Nuts' },
  { _id: 'cat-4', name: 'Bakery', slug: 'bakery', icon: '🍞', description: 'Artisanal Breads, Cookies, Buns & Cakes' },
  { _id: 'cat-5', name: 'Fruits & Vegetables', slug: 'fruits-vegetables', icon: '🥬', description: 'Farm Fresh Organic Veggies, Exotic Fruits & Greens' },
  { _id: 'cat-6', name: 'Instant Food', slug: 'instant-food', icon: '🍜', description: 'Maggi Noodles, Soups, Pasta & Ready Meals' },
  { _id: 'cat-7', name: 'Rice & Atta', slug: 'rice-atta', icon: '🌾', description: 'Sharbati Whole Wheat Atta, Basmati Rice & Grains' },
  { _id: 'cat-8', name: 'Pulses & Dals', slug: 'pulses-dals', icon: '🫘', description: 'Unpolished Dals, Rajma, Chana & Pulses' },
  { _id: 'cat-9', name: 'Beverages', slug: 'beverages', icon: '🥤', description: 'Tea, Coffee, Cold Pressed Juices & Soft Drinks' },
  { _id: 'cat-10', name: 'Personal Care', slug: 'personal-care', icon: '🧼', description: 'Skincare, Haircare & Hygiene Essentials' },
  { _id: 'cat-11', name: 'Household', slug: 'household', icon: '🧹', description: 'Detergents, Surface Cleaners & Tissue Papers' },
  { _id: 'cat-12', name: 'Fashion & Apparel', slug: 'fashion-apparel', icon: '👕', description: 'Trendy T-Shirts, Kurtis, Denim Jeans, Footwear & Accessories' },
  { _id: 'cat-13', name: 'Baby Care', slug: 'baby-care', icon: '👶', description: 'Diapers, Baby Wipes & Gentle Care' },
  { _id: 'cat-14', name: 'Pet Supplies', slug: 'pet-supplies', icon: '🐾', description: 'Dog Food, Cat Treats & Pet Care' }
];

export const MOCK_PRODUCTS = [
  // Dairy & Breakfast
  {
    _id: 'prod-1',
    name: 'Amul Taaza Homogenised Toned Milk',
    brand: 'Amul',
    category: 'Dairy & Breakfast',
    subCategory: 'Milk',
    price: 27,
    originalPrice: 28,
    stock: 150,
    weight: '500 ml',
    unit: 'pouch',
    rating: 4.9,
    reviewCount: 320,
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop'],
    description: 'Fresh pasteurised toned milk from Amul. Homogenised to ensure uniform fat distribution and creamy taste. Rich in Calcium and Vitamin A & D.',
    keyFeatures: ['No Added Preservatives', 'Pasteurised & Homogenised', 'Chilled Express Delivery'],
    ingredients: 'Toned Milk, Vitamin A & D2',
    nutrition: { calories: '58 kcal', protein: '3.1 g', carbs: '4.7 g', fat: '3.0 g' },
    storageInfo: 'Store in refrigerator at 4°C or below.',
    isVeg: true,
    dietaryTags: ['Veg', 'Calcium-Rich'],
    isBestSeller: true,
    isTrending: true,
    isDeal: false
  },
  {
    _id: 'prod-2',
    name: 'Amul Salted Pasteurized Butter',
    brand: 'Amul',
    category: 'Dairy & Breakfast',
    subCategory: 'Butter',
    price: 56,
    originalPrice: 60,
    stock: 90,
    weight: '100 g',
    unit: 'pack',
    rating: 4.9,
    reviewCount: 410,
    images: ['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop'],
    description: 'Iconic golden butter crafted from pure cow milk with rich aroma and balanced saltiness.',
    keyFeatures: ['Made from Pure Cream', 'Iconic Taste', 'Perfect for Toast & Parathas'],
    ingredients: 'Butter, Common Salt',
    nutrition: { calories: '717 kcal', protein: '0.6 g', carbs: '0.8 g', fat: '80 g' },
    storageInfo: 'Keep refrigerated.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: false,
    isDeal: true
  },
  {
    _id: 'prod-3',
    name: 'Amul Fresh Malai Paneer Block',
    brand: 'Amul',
    category: 'Dairy & Breakfast',
    subCategory: 'Paneer',
    price: 90,
    originalPrice: 105,
    stock: 50,
    weight: '200 g',
    unit: 'pack',
    rating: 4.8,
    reviewCount: 130,
    images: ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop'],
    description: 'Soft, melt-in-mouth cottage cheese crafted from pure fresh milk. High in natural protein.',
    keyFeatures: ['Super Soft Texture', 'Rich in Milk Protein', 'Vacuum Sealed'],
    ingredients: 'Milk Solids, Citric Acid',
    nutrition: { calories: '265 kcal', protein: '18.3 g', carbs: '1.2 g', fat: '20.8 g' },
    storageInfo: 'Keep refrigerated.',
    isVeg: true,
    dietaryTags: ['Veg', 'High-Protein'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },

  // Snacks & Munchies
  {
    _id: 'prod-4',
    name: "Lay's American Style Cream & Onion Potato Chips",
    brand: "Lay's",
    category: 'Snacks & Munchies',
    subCategory: 'Chips',
    price: 20,
    originalPrice: 20,
    stock: 150,
    weight: '52 g',
    unit: 'pouch',
    rating: 4.8,
    reviewCount: 810,
    images: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop'],
    description: 'Crispy wafer thin potato chips infused with rich American cream and spring onion seasoning.',
    keyFeatures: ['Iconic Green Pack', 'Rich Cream & Onion Taste', 'Crispy Golden Chips'],
    ingredients: 'Potatoes, Edible Vegetable Oil, Sugar, Salt, Milk Solids, Onion Powder',
    nutrition: { calories: '542 kcal', protein: '7.1 g', carbs: '52 g', fat: '34 g' },
    storageInfo: 'Store in cool dry place.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: false
  },
  {
    _id: 'prod-5',
    name: 'Britannia Bourbon Original Chocolate Creme Biscuits',
    brand: 'Britannia',
    category: 'Snacks & Munchies',
    subCategory: 'Biscuits',
    price: 35,
    originalPrice: 40,
    stock: 120,
    weight: '150 g',
    unit: 'pack',
    rating: 4.9,
    reviewCount: 680,
    images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop'],
    description: 'Iconic chocolate sandwich biscuits with crunchy sugar-sprinkled biscuits and rich chocolate cream filling.',
    keyFeatures: ['Rich Chocolate Creme', 'Crunchy Sugar Crystals', 'Iconic Biscuit'],
    ingredients: 'Refined Wheat Flour, Sugar, Edible Vegetable Oil, Cocoa Solids',
    nutrition: { calories: '485 kcal', protein: '5.5 g', carbs: '71 g', fat: '20 g' },
    storageInfo: 'Store in cool dry place.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },
  {
    _id: 'prod-6',
    name: 'Cadbury Dairy Milk Silk Chocolate Bar',
    brand: 'Cadbury',
    category: 'Snacks & Munchies',
    subCategory: 'Chocolates',
    price: 80,
    originalPrice: 90,
    stock: 140,
    weight: '60 g',
    unit: 'bar',
    rating: 4.9,
    reviewCount: 950,
    images: ['https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop'],
    description: 'Smoother, creamier, and silkier chocolate made with the finest cocoa and creamy milk solids.',
    keyFeatures: ['Silk Smooth Texture', 'Pure Milk Chocolate', 'Melts in Your Mouth'],
    ingredients: 'Sugar, Milk Solids, Cocoa Butter, Cocoa Solids',
    nutrition: { calories: '532 kcal', protein: '8 g', carbs: '58 g', fat: '31 g' },
    storageInfo: 'Store in cool dry place (15-20°C).',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },

  // Oils & Spices
  {
    _id: 'prod-7',
    name: 'Fortune Kachi Ghani Pure Mustard Oil',
    brand: 'Fortune',
    category: 'Oils & Spices',
    subCategory: 'Cooking Oils',
    price: 145,
    originalPrice: 175,
    stock: 65,
    weight: '1 L',
    unit: 'pouch',
    rating: 4.8,
    reviewCount: 280,
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop'],
    description: 'Cold-pressed traditional Kachi Ghani mustard oil made from selected mustard seeds.',
    keyFeatures: ['Cold Pressed Extraction', 'Pungent Aroma & Authentic Taste', 'Rich in Omega 3 & 6'],
    ingredients: '100% Pure Mustard Oil',
    nutrition: { calories: '900 kcal', protein: '0 g', carbs: '0 g', fat: '100 g' },
    storageInfo: 'Store in cool dry place away from sunlight.',
    isVeg: true,
    dietaryTags: ['Veg', 'Heart-Healthy'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },
  {
    _id: 'prod-8',
    name: 'Everest Garam Masala Powder',
    brand: 'Everest',
    category: 'Oils & Spices',
    subCategory: 'Spices',
    price: 90,
    originalPrice: 105,
    stock: 95,
    weight: '100 g',
    unit: 'box',
    rating: 4.9,
    reviewCount: 510,
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop'],
    description: 'Aromatic blend of 13 hand-picked whole spices, freshly ground to perfection.',
    keyFeatures: ['13 Whole Spice Blend', 'Freshly Ground', 'Authentic Taste'],
    ingredients: 'Coriander, Cumin, Black Pepper, Cardamom, Cinnamon, Cloves',
    nutrition: { calories: '370 kcal', protein: '10 g', carbs: '45 g', fat: '15 g' },
    storageInfo: 'Store in cool dry place.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },

  // Fruits & Vegetables
  {
    _id: 'prod-9',
    name: 'Farm Fresh Organic Hybrid Tomatoes',
    brand: 'Big Market Fresh',
    category: 'Fruits & Vegetables',
    subCategory: 'Vegetables',
    price: 32,
    originalPrice: 40,
    stock: 200,
    weight: '1 kg',
    unit: 'pack',
    rating: 4.8,
    reviewCount: 420,
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop'],
    description: 'Juicy, farm-harvested red tomatoes rich in Lycopene and Vitamin C.',
    keyFeatures: ['Farm Fresh Daily', 'Residue-Free Organic', 'Firm & Juicy'],
    ingredients: 'Fresh Tomatoes',
    nutrition: { calories: '18 kcal', protein: '0.9 g', carbs: '3.9 g', fat: '0.2 g' },
    storageInfo: 'Keep at room temperature or refrigerate.',
    isVeg: true,
    dietaryTags: ['Veg', 'Organic'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },
  {
    _id: 'prod-10',
    name: 'Fresh Shimla Red Apples',
    brand: 'Big Market Fresh',
    category: 'Fruits & Vegetables',
    subCategory: 'Fruits',
    price: 160,
    originalPrice: 190,
    stock: 100,
    weight: '1 kg (approx 4-5 pcs)',
    unit: 'pack',
    rating: 4.9,
    reviewCount: 310,
    images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop'],
    description: 'Crispy, sweet orchard apples sourced directly from Shimla valleys.',
    keyFeatures: ['Direct from Orchards', 'High Fiber', 'Naturally Sweet'],
    ingredients: 'Fresh Apples',
    nutrition: { calories: '52 kcal', protein: '0.3 g', carbs: '14 g', fat: '0.2 g' },
    storageInfo: 'Refrigerate for maximum crispness.',
    isVeg: true,
    dietaryTags: ['Veg', 'Fiber-Rich'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },

  // Instant Food
  {
    _id: 'prod-11',
    name: 'Maggi 2-Minute Masala Noodles',
    brand: 'Maggi',
    category: 'Instant Food',
    subCategory: 'Noodles',
    price: 56,
    originalPrice: 60,
    stock: 250,
    weight: '280 g (Pack of 4)',
    unit: 'pack',
    rating: 4.9,
    reviewCount: 1200,
    images: ['https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop'],
    description: 'India\'s favorite 2-minute instant noodles with the classic spicy roasted taste maker.',
    keyFeatures: ['Iconic Taste', 'Ready in 2 Minutes', 'Fortified with Iron'],
    ingredients: 'Wheat Flour, Palm Oil, Salt, Roasted Spices',
    nutrition: { calories: '380 kcal', protein: '8 g', carbs: '55 g', fat: '14 g' },
    storageInfo: 'Store in cool dry place.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: false
  },

  // Beverages
  {
    _id: 'prod-12',
    name: 'Tata Tea Gold Premium Black Tea',
    brand: 'Tata Tea',
    category: 'Beverages',
    subCategory: 'Tea',
    price: 290,
    originalPrice: 340,
    stock: 80,
    weight: '500 g',
    unit: 'pack',
    rating: 4.9,
    reviewCount: 640,
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop'],
    description: 'Unique blend of fine CTC tea leaves with gently rolled long leaves for rich aroma and brisk flavor.',
    keyFeatures: ['Gently Rolled Long Leaves', 'Rich Golden Color', 'Irresistible Taste'],
    ingredients: '100% Black Tea',
    nutrition: { calories: '0 kcal', protein: '0 g', carbs: '0 g', fat: '0 g' },
    storageInfo: 'Store in airtight container.',
    isVeg: true,
    dietaryTags: ['Veg'],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },

  // Fashion & Apparel
  {
    _id: 'prod-13',
    name: 'Classic Cotton Crew Neck T-Shirt - Navy Blue',
    brand: "Levi's",
    category: 'Fashion & Apparel',
    subCategory: 'Men Fashion',
    price: 599,
    originalPrice: 999,
    stock: 45,
    weight: '250 g',
    unit: 'piece',
    rating: 4.8,
    reviewCount: 180,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop'],
    description: '100% Premium Bio-Washed Combed Cotton t-shirt. Ultra-soft breathable fabric for everyday comfort.',
    keyFeatures: ['100% Combed Cotton', 'Bio-Washed Finish', 'Pre-Shrunk Fabric'],
    ingredients: '100% Cotton',
    nutrition: {},
    storageInfo: 'Machine wash cold with like colors.',
    isVeg: true,
    dietaryTags: [],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  },
  {
    _id: 'prod-14',
    name: 'Floral Print Anarkali Kurti & Dupatta Set',
    brand: 'BIBA',
    category: 'Fashion & Apparel',
    subCategory: 'Women Fashion',
    price: 1299,
    originalPrice: 2499,
    stock: 30,
    weight: '400 g',
    unit: 'set',
    rating: 4.9,
    reviewCount: 220,
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop'],
    description: 'Elegantly tailored floral print ethnic Kurti set crafted from lightweight breathable viscose rayon fabric.',
    keyFeatures: ['Elegant Floral Print', 'Lightweight Viscose Rayon', 'Includes Matching Dupatta'],
    ingredients: 'Viscose Rayon',
    nutrition: {},
    storageInfo: 'Hand wash gently.',
    isVeg: true,
    dietaryTags: [],
    isBestSeller: true,
    isTrending: true,
    isDeal: true
  }
];

export const MOCK_USER = {
  _id: 'usr-customer-1',
  name: 'Rahul Sharma',
  email: 'customer@bigmarket.com',
  role: 'customer',
  phone: '+91 98123 45678',
  coins: 450,
  token: 'mock-jwt-token-9988776655',
  addresses: [
    {
      _id: 'addr-1',
      title: 'Home',
      name: 'Rahul Sharma',
      phone: '+91 98123 45678',
      street: 'Flat 402, Green Meadows, Link Road',
      apartment: 'Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400050',
      isDefault: true
    }
  ]
};

export const MOCK_COUPONS = [
  { _id: 'c-1', code: 'WELCOME50', discountPercent: 50, maxDiscount: 100, minOrderValue: 199, description: '50% OFF up to ₹100 on your first 3 orders!' },
  { _id: 'c-2', code: 'FRESH20', discountPercent: 20, maxDiscount: 150, minOrderValue: 299, description: '20% OFF on all fresh fruits, veggies & dairy products' },
  { _id: 'c-3', code: 'BIGMARKET100', discountPercent: 15, maxDiscount: 200, minOrderValue: 499, description: 'Flat 15% OFF on orders above ₹499' }
];

export const MOCK_ORDERS = [
  {
    _id: 'BM-89241',
    orderNumber: 'BM-89241',
    user: MOCK_USER._id,
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 2, price: 27 },
      { product: MOCK_PRODUCTS[3], quantity: 1, price: 20 }
    ],
    shippingAddress: MOCK_USER.addresses[0],
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    subtotal: 74,
    discountAmount: 0,
    deliveryFee: 15,
    totalAmount: 89,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString()
  }
];

export const MOCK_TRAFFIC_STATS = {
  activeConnections: 48,
  systemLoad: 'Normal (12%)',
  serverHealth: 'Optimal 🟢',
  status: 'OK',
  cacheHitRatio: '94.2%'
};
